# Generated by Django 5.1.6 on 2025-03-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tour_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_payments', to='tour.tourbooking'),
        ),
    ]
