# Generated by Django 5.1.6 on 2025-03-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='tour/ThumbnailImage/')),
                ('thumbnail_cloudflare_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('reviews', models.CharField(blank=True, max_length=5000, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=5000, null=True)),
                ('knw_before_go', models.CharField(blank=True, max_length=5000, null=True)),
                ('group_size', models.CharField(blank=True, max_length=5000, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
                ('inclution', models.TextField(blank=True, null=True)),
                ('exclusion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=10000, null=True)),
                ('trip_url', models.CharField(blank=True, max_length=10000, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('adult_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('youth_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('free_cancellation', models.BooleanField(blank=True, default=False, null=True)),
                ('select_bus', models.CharField(blank=True, max_length=50, null=True)),
                ('is_bokun_url', models.BooleanField(blank=True, default=True, null=True)),
                ('available_dates', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_booking_agent', to='member.member')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TourContents',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('youth_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('value', 'Value')], default='percentage', max_length=20, null=True)),
                ('participants', models.JSONField(blank=True, null=True)),
                ('selected_date', models.DateField(blank=True, null=True)),
                ('selected_time', models.TimeField(blank=True, null=True)),
                ('payWithCash', models.BooleanField(blank=True, db_default=False, default=False, null=True)),
                ('payWithStripe', models.BooleanField(blank=True, db_default=False, default=False, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('is_agent', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('email_pdf', models.FileField(blank=True, null=True, upload_to='tour_booking_pdf/')),
                ('url', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to='member.member')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('traveller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='payments.traveller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.tourcontent')),
            ],
            options={
                'verbose_name_plural': 'TourBooking',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TourContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour/ContentImage/')),
                ('cloudflare_image', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tour_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_content_images', to='tour.tourcontent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TourContentImages',
                'ordering': ('-id',),
            },
        ),
    ]
