# Generated by Django 5.1.6 on 2025-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='booking_invoice',
            field=models.FileField(blank=True, null=True, upload_to='tour_booking_invoice_pdf/'),
        ),
    ]
