# Generated by Django 5.1.6 on 2025-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_booking_invoice_tourbooking_booking_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='coupon_applied_final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='payWithCash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='payWithStripe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
