# Generated by Django 5.1.6 on 2025-03-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('tour', '0003_tourbooking_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_currency', to='payments.payment'),
        ),
    ]
